### ISSUE TITLE
Could not find cookbook chef-terraform in your cookbook path, skipping it

### ISSUE THREAD

**Issue by kishan0001** [haidangwa/chef-terraform#1]
Hi,

I have clone the repo. Now i am trying to upload this cookbook to the chef management console. Whenever i am doing this i am getting an error of "Could not find cookbook chef-terraform in your cookbook path, skipping it".

I am getting this error even though my cookbook path which specified in knife.rb is correct. As i am able upload other cookbooks to chef management console.

Please help.

**Comment by kbuchsicf** [comment]
Suggestion: ensure you have a metadata.rb defined name that matches that which you are trying to upload. The directory name is not used to name the cookbook.

**Comment by zerolaser** [comment]
@kishan0001 the name of the cookbook is terraform not chef-terraform. 
if this cookbook is in your cookbooks_path. just run 
`knife cookbook upload terraform` that should work for you.
